# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Σπίγγου Ελισσάβετ
title: Εκπαιδευτικός
email: elsa.spingou@gmail.com
website: https://elizabeth-spingou.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  elizabeth-spingou
# facebook_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant

# Additional icon links
additional_links:
- title: Print version
  icon: far fa-file-pdf
  url: https://github.com/elizabeth-spingou/elizabeth-spingou.github.io/blob/master/Spingou_Elisabeth_CV.pdf?raw=true

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Eκπαιδευτικός με μεγάλη εμπειρία στο χώρο της εκπαίδευσης. Αγαπώ τα παιδιά και προσπαθώ να δημιουργώ το καλύτερο κλίμα γι' αυτά.
  
  Στόχος μου είναι η γνώση και η εξειδίκευση στην εκπαιδευτική κοινότητα των ατόμων που χρήζουν ειδική αντιμετώπιση.


content:
  - title: Εκπαίδευση # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Παν/μιο Ιωαννίνων
        caption: 1999 - 2003
        sub_title: Παιδαγωγικο Τμήμα Δημοτικης Εκπαιδευσης 7,25 "λιαν καλως"
       
        description: | # this will include new lines to allow paragraphs
          Tο Παιδαγωγικό Tμήμα Δημοτικής Eκπαίδευσης (ΠΤΔΕ) του Πανεπιστημίου Iωαννίνων ιδρύθηκε με το N. 1268/82 και άρχισε να λειτουργεί το 1984. Οι στόχοι που τίθενται από το Πρόγραμμα Σπουδών πραγματοποιούνται μέσα από τρία αλληλένδετα επίπεδα μάθησης, με υπόβαθρο πάντα τη δυναμική σύνδεση παιδαγωγικής θεωρίας και εκπαιδευτικής πράξης.

      - layout: left
        title: Κέντρο Εκπαιδεύσεως και Αποκαταστάσεως Tυφλών
        caption: 2017
        sub_title: Σύστημα Braille
        description: | # this will include new lines to allow paragraphs
          Πιστοποίηση γνώσης του συστήματος γραφής και ανάγνωσης τυφλών baille.

          To Braille είναι το σύστημα γραφής και ανάγνωσης των τυφλών, το οποίο έχει αναγνωριστεί επίσημα από την πολιτεία με τον νόμο 36/99 του 2008. Δημιουργήθηκε από τον Louis Braille το 1829, ο οποίος έχασε την όρασή του ενώ ήταν ακόμα παιδί στο εργαστήριο του πατέρα του το 1824 σε ηλικία 15 χρονών.

      - layout: left
        title: First Certificate In English 
        caption: 1995
        sub_title: Cambridge University
        description: | 
          English qualification proves competency in speaking and writing English well enough to work or study in an English-speaking environment.

          Level of qualification: Upper intermediate = B2 on the Common European Framework.

  - title: Ειδικές Γνώσεις
    layout: list
    content:
      - layout: left
        title: Υπουργείο Παιδείας και Θρησκευμάτων
        caption: Χρήση Η/Υ
        description: |
          Πιστοποίηση δεξιοτήτων και γνώσεων στις τεχνολογίες πληροφορίας και επικοινωνίας του υπουργείου παιδείας επίπεδο A.

  - title: Σεμινάρια
    layout: text
    content: |

      * Βιωματικό Σεμιναρίου «τα ιστολογία στην εκπαίδευση», 2012

      * Βιωματικό Σεμιναρίου «στοματική υγιεινή», 2013

      * Βιωματικό Σεμιναρίου «δημιουργική γραφή», 2016

      * Υλοποίηση προγράμματος περιβαλλοντικής εκπ/σης «μέλισσας εργα-ανθρωπων αγαθα», 2017


  
  - title: Επαγγελματική Εμπειρία # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Εκπαιδευτικός 
        sub_title: Αναπληρώτρια
        caption: 2003 – 2005
        description: |
          |Σχολείο|
          |:----|
          |Ολοήμερο Δημοτικό Σχολείο Γομοστού|
          |Δημοτικό Σχολείο Βίγλας ‘Αρτας|
      
      - layout: left
        title: Εκπαιδευτικός 
        sub_title: Μόνιμη Οργανική Θέση 
        caption: 2005 – Σήμερα
        description: | # this will include new lines to allow paragraphs
            |Σχολείο|Σχολείο Συν.|
            |:----|:----|
            |Ολοήμερο Δημοτικό Σχολείο Όθος Καρπάθου|3ο Δημοτικό Ανατολής|
            |2ο Δημοτικό Φιλιατων|2ο Δημοτικό Κόνιτσας|
            |1ο Δημοτικό Σχολείο Παραμυθιας|2ο Δημοτικό Κόνιτσας|
            |2ο Δημοτικό Φιλιατων|Δημοτικό Σχολείο Νέας Μουσιωτίτσας|
            |2ο Δ.Σ. Φιλιατων-Άδεια Ανατροφής|27ο Δημοτικό Ιωάννινων|
            |2ο Δημοτικό Φιλιατων|Δημοτικό Σχολείο Νέας Μουσιωτίτσας|
            |1ο Δημοτικό Μετσόβου (Τοσίτσειο)|3ο Δημοτικό Ιωάννινων (Μαρουτσειο)|
            |2ο Δημοτικό Φιλιατων|Δημοτικό Σχολείο Νέας Μουσιωτίτσας|
            |1ο Δημοτικό Μετσόβου (Τοσίτσειο)|9ο Διαπολιτισμικό Δημοτικό Σχολείο Ιωάννινων|
            |1ο Δημοτικό Μετσόβου (Τοσίτσειο)|**Δημοτικό Σχολείο Νέας Μουσιωτίτσας**|
            |2ο Δημοτικό Κονιτσας| |

            Αναλυτική εκπαιδευτική εμπειρία διαθέσιμη [εδώ](https://github.com/elizabeth-spingou/elizabeth-spingou.github.io/blob/master/elsa-work-experience.xlsx?raw=true).


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag