# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Σπίγγου Ελισσάβετ
title: Εκπαιδευτικός
email: elsa.spingou@gmail.com
website: https://elizabeth-spingou.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  elizabeth-spingou
# facebook_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Είμαι εκπαιδευτικός με μεγάλη εμπειρία στο χώρο της εκπαίδευσης.Αγαπω τα παιδιά και προσπαθώ να δημιουργώ το καλύτερο κλίμα γι' αυτά.
  
  Στοχος μου είναι η γνώση και η εξειδίκευση στην εκπαιδευτική κοινότητα των ατόμων που χρήζουν ειδική αντιμετώπιση.


content:
  - title: Εκπαίδευση # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Παν/μιο Ιωαννίνων
        caption: 1999 - 2003
        sub_title: Παιδαγωγικο Τμήμα Δημοτικης Εκπαιδευσης 7,25 "λιαν καλως"
       
        description: | # this will include new lines to allow paragraphs
          Tο Παιδαγωγικό Tμήμα Δημοτικής Eκπαίδευσης (ΠΤΔΕ) του Πανεπιστημίου Iωαννίνων ιδρύθηκε με το N. 1268/82 και άρχισε να λειτουργεί το 1984. Οι στόχοι που τίθενται από το Πρόγραμμα Σπουδών πραγματοποιούνται μέσα από τρία αλληλένδετα επίπεδα μάθησης, με υπόβαθρο πάντα τη δυναμική σύνδεση παιδαγωγικής θεωρίας και εκπαιδευτικής πράξης.

      - layout: left
        title: Κέντρο Εκπαιδεύσεως και Αποκαταστάσεως Tυφλών
        caption: 2017
        sub_title: Σύστημα Braille
        description: | # this will include new lines to allow paragraphs
          Πιστοποίηση γνώσης του συστήματος γραφής και ανάγνωσης τυφλών baille.

          To Braille είναι το σύστημα γραφής και ανάγνωσης των τυφλών, το οποίο έχει αναγνωριστεί επίσημα από την πολιτεία με τον νόμο 36/99 του 2008. Δημιουργήθηκε από τον Louis Braille το 1829, ο οποίος έχασε την όρασή του ενώ ήταν ακόμα παιδί στο εργαστήριο του πατέρα του το 1824 σε ηλικία 15 χρονών.

      - layout: top-middle
        title: First Certificate In English 
        caption: 1996
        sub_title: Cambridge University
        description: | # this will include new lines to allow paragraphs


  
  - title: Επαγγελματική Εμπειρία # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  

  - title: Ειδικές Γνώσεις
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag